config/routes.rb
Rails.application.routes.draw do
  resources :videos
  root 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_content_type :file, content_type: ["video/mp4", "application/mp4"]
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :find_video, except: [:index, :new, :create]

  def index
    @videos = Video.all.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:notice] = "Success!"
      redirect_to videos_path
    else
      flash[:alert] = "You can only upload mp4 videos!"
      redirect_to new_video_path
    end
  end

  def destroy
    @video.destroy
    flash[:notice] = "Video Deleted!"
    redirect_to videos_path
  end

  private

  def find_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:file, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mp4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>

<div class="container">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'mp4', videos_path, class: "navbar-brand"%>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', videos_path %></li>
        <li><%= link_to 'Add Video', new_video_path %></li>
      </ul>
    </div>
  </nav>
  <% if notice %>
    <p class="alert alert-success"><%= sanitize(notice) %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= sanitize(alert) %></p>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for @video, html: {multi_part: true} do |f| %>
  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form_control' %>
  </div>
  <div class="form-group">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>
  <%= f.submit %>
<% end %>

app/views/videos/index.html.erb
<center><%= link_to 'Add Video', new_video_path, class: 'btn btn-info btn-lg' %></center>
<% @videos.each do |video| %>
  <ul>
    <li>
      <h1><%= video.title %></h1>
      <video width="400" controls>
        <source src=<%= video.file %> type="video/mp4">
        Your browser does not support HTML5 video.
      </video>
      <br>
      <%= link_to 'Delete', video_path(video), data: { confirm: 'Are you sure?', method: 'delete'}%>
    </li>
  </ul>
  <% end %>

app/views/videos/new.html.erb
<%= render 'form' %>